<template>
    <nav class="flex justify-items-center mt-60px">
        <ul class="flex space-x-6">
            <li>
                <a
                    href="#"
                    class="
                        text-gray-300
                        hover:text-white
                        px-3
                        py-2
                        text-sm
                        font-medium
                    "
                    >HOME</a
                >
            </li>
            <li>
                <a
                    href="#"
                    class="
                        text-gray-300
                        hover:text-white
                        px-3
                        py-2
                        text-sm
                        font-medium
                    "
                    >SOBRE NÓS</a
                >
            </li>
            <li>
                <a
                    href="#"
                    class="
                        text-gray-300
                        hover:text-white
                        px-3
                        py-2
                        text-sm
                        font-medium
                    "
                    >SEJA REVENDEDOR(A)</a
                >
            </li>
            <li>
                <a
                    href="#"
                    class="
                        text-gray-300
                        hover:text-white
                        px-3
                        py-2
                        rounded-md
                        text-sm
                        font-medium
                    "
                    >PRODUTOS</a
                >
            </li>
            <li>
                <a
                    href="#"
                    class="
                        text-gray-300
                        hover:text-white
                        px-3
                        py-2
                        rounded-md
                        text-sm
                        font-medium
                    "
                    >CONTATO</a
                >
            </li>
        </ul>
    </nav>
</template>
